app = "rough-sun-2523"
kill_signal = "SIGINT"
primary_region = "ams"

[env]
PORT = "8080"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 0