# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Test
on:
  push:
    branches-ignore:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - run: dart pub get
      - run: dart format --output=none .
      - run: dart analyze
      - run: dart test
